name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p dist
          echo '<!DOCTYPE html>
          <html>
          <body>
            <h1>MonkeyClash</h1>
          </body>
          </html>' > dist/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: monkeyclash-dist
          path: dist/
          retention-days: 3
