name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build game
        run: |
          mkdir -p dist
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>MonkeyClash</title>
          </head>
          <body>
            <h1>MonkeyClash</h1>
            <div id="game"></div>
          </body>
          </html>' > dist/index.html
          # Add your game files
          cp *.py dist/
      - uses: actions/upload-artifact@v4
        with:
          name: game-dist
          path: dist/
          retention-days: 1
