name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          # Add your build commands here
          echo "Building the project..."
          mkdir -p build/web
          touch build/web/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/web
