name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p build/web
          echo "<h1>MonkeyClash Game</h1>" > build/web/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/web
          retention-days: 5
